with (import <nixpkgs> {});

pkgs.mkShell {

  buildInputs = [

    # python
    python39
    python39Packages.venvShellHook

    # node
    nodejs-16_x

    # need to specify the yarn version here, else it points at the wrong one...
    # alternative we install yarn manually
    (yarn.override {
      nodejs = nodejs-16_x;
    })
  ];

  venvDir = "./.nix-venv";

  postVenvCreation = ''
    pip install -U pip wheel pip-tools
  '';

  postShellHook = ''
    ./sync-requirements.sh
    yarn install
    export PATH=$(pwd)/node_modules/.bin:$PATH

    if [ ! -f .env ]; then
      touch .env
      echo "#Autogenerated, please add real values" >> .env
      echo "#WEB3_INFURA_PROJECT_ID=xxx" >> .env
    fi
  '';
}

